-- =========================================================================
-- Phase IV & V: Database Creation and Table Implementation
-- Project Name: 32217_2025_EVENT_MANAGEMENT_DB
-- =========================================================================

-- Note: Connect to your custom Pluggable Database (PDB) via SQL Developer before running.

-- 1. Core Tables Creation
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('Organizer', 'Attendee', 'Admin')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Venues (
    venue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(200) NOT NULL,
    capacity NUMBER NOT NULL CHECK (capacity > 0)
);

CREATE TABLE Events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(150) NOT NULL,
    event_date DATE NOT NULL,
    venue_id NUMBER REFERENCES Venues(venue_id),
    organizer_id NUMBER REFERENCES Users(user_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id NUMBER REFERENCES Events(event_id) ON DELETE CASCADE,
    attendee_id NUMBER REFERENCES Users(user_id),
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'Confirmed' CHECK (status IN ('Confirmed', 'Cancelled'))
);
